2018-03-12 21:54:28,918 INFO: Microblog startup [in /home/bers/PycharmProjects/microblog/app/__init__.py:45]
2018-03-16 22:46:06,827 INFO: Microblog startup [in /home/bers/PycharmProjects/microblog/app/__init__.py:45]
2018-03-16 22:46:19,568 INFO: Microblog startup [in /home/bers/PycharmProjects/microblog/app/__init__.py:45]
2018-03-16 23:02:48,652 INFO: Microblog startup [in /home/bers/PycharmProjects/microblog/app/__init__.py:45]
2018-03-16 23:08:26,429 INFO: Microblog startup [in /home/bers/PycharmProjects/microblog/app/__init__.py:45]
2018-04-15 21:05:30,724 INFO: Microblog startup [in /home/bers/PycharmProjects/microblog/app/__init__.py:45]
2018-04-15 21:05:40,642 ERROR: Exception on / [GET] [in /home/bers/PycharmProjects/microblog/venv/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/bers/PycharmProjects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bers/PycharmProjects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bers/PycharmProjects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/bers/PycharmProjects/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/bers/PycharmProjects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bers/PycharmProjects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/bers/PycharmProjects/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/bers/PycharmProjects/microblog/app/routes.py", line 30, in index
    return render_template("index.html", title='Home Page', form=form, posts=posts)
UnboundLocalError: local variable 'posts' referenced before assignment
2018-04-15 21:09:41,502 INFO: Microblog startup [in /home/bers/PycharmProjects/microblog/app/__init__.py:45]
2018-04-15 21:09:44,940 ERROR: Exception on / [GET] [in /home/bers/PycharmProjects/microblog/venv/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/bers/PycharmProjects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bers/PycharmProjects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bers/PycharmProjects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/bers/PycharmProjects/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/bers/PycharmProjects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bers/PycharmProjects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/bers/PycharmProjects/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/bers/PycharmProjects/microblog/app/routes.py", line 39, in index
    return render_template("index.html", title='Home Page', form=form, posts=posts)
UnboundLocalError: local variable 'posts' referenced before assignment
2018-04-15 21:09:47,095 ERROR: Exception on /index [GET] [in /home/bers/PycharmProjects/microblog/venv/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/bers/PycharmProjects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bers/PycharmProjects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bers/PycharmProjects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/bers/PycharmProjects/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/bers/PycharmProjects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bers/PycharmProjects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/bers/PycharmProjects/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/bers/PycharmProjects/microblog/app/routes.py", line 39, in index
    return render_template("index.html", title='Home Page', form=form, posts=posts)
UnboundLocalError: local variable 'posts' referenced before assignment
